name: ✨ Feature Request
description: Request a new feature or enhancement
title: "[Suggestion] <Extension name>:"
labels: enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: 📝 Provide a description of the new feature
      description: What is the expected behavior of the proposed feature? What is the scenario this would be used?
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: ➕ Additional Information
      description: Give us some additional information on the feature request like proposed solutions, links, screenshots, etc.
